# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0002_auto_20170921_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='user',
            new_name='entrant',
        ),
    ]
