# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0012_auto_20171003_1559'),
        ('fpl', '0003_auto_20170921_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('leagues.payout',),
        ),
    ]
