# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fpl', '0004_payout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassicLeague',
            new_name='FPLLeague',
        ),
        migrations.CreateModel(
            name='ClassicLeague',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('fpl.fplleague',),
        ),
        migrations.CreateModel(
            name='HeadToHeadLeague',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('fpl.fplleague',),
        ),
    ]
