# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0013_auto_20171023_1656'),
        ('fpl', '0007_auto_20171028_0821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payout',
        ),
        migrations.CreateModel(
            name='FPLPayout',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('leagues.payout',),
        ),
        migrations.AddField(
            model_name='gameweek',
            name='end_date',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClassicPayout',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('fpl.fplpayout',),
        ),
        migrations.CreateModel(
            name='HeadToHeadPayout',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('fpl.fplpayout',),
        ),
    ]
