# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0013_auto_20171023_1656'),
        ('fpl', '0008_auto_20171128_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fplleague',
            name='league',
        ),
        migrations.RemoveField(
            model_name='classicleague',
            name='fpl_league',
        ),
        migrations.RemoveField(
            model_name='headtoheadleague',
            name='fpl_league',
        ),
        migrations.AddField(
            model_name='classicleague',
            name='fpl_league_id',
            field=models.IntegerField(default=587157, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classicleague',
            name='league',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='leagues.League'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headtoheadleague',
            name='fpl_league_id',
            field=models.IntegerField(default=588660, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headtoheadleague',
            name='league',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='leagues.League'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FPLLeague',
        ),
    ]
