# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 22:24
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fpl', '0009_auto_20171129_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headtoheadmatch',
            name='participants',
        ),
        migrations.AddField(
            model_name='headtoheadmatch',
            name='manager_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='fpl.Manager'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headtoheadmatch',
            name='manager_2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='fpl.Manager'),
            preserve_default=False,
        ),
    ]
