# Generated by Django 2.0.1 on 2018-02-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0010_auto_20171130_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicleague',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='headtoheadleague',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
