# Generated by Django 2.0.2 on 2018-05-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_league_season'),
        ('fpl', '0012_gameweek_season'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameweek',
            unique_together={('season', 'number')},
        ),
    ]
