# Generated by Django 2.1 on 2018-08-16 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_league_season'),
        ('fpl', '0014_auto_20180815_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leagues.Season'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manager',
            name='fpl_manager_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='manager',
            unique_together={('season', 'fpl_manager_id')},
        ),
    ]
