# Generated by Django 2.1 on 2018-08-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0016_auto_20180816_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classicleague',
            name='fpl_league_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='headtoheadleague',
            name='fpl_league_id',
            field=models.IntegerField(),
        ),
    ]
