# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_entry', models.BooleanField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.IntegerField()),
                ('score', models.IntegerField()),
                ('league_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.LeagueMembership')),
            ],
        ),
        migrations.AddField(
            model_name='leaguemembership',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.Manager'),
        ),
        migrations.AddField(
            model_name='league',
            name='league_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.LeagueType'),
        ),
        migrations.AddField(
            model_name='league',
            name='managers',
            field=models.ManyToManyField(blank=True, through='leagues.LeagueMembership', to='leagues.Manager'),
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together=set([('gameweek', 'league_membership')]),
        ),
    ]
