# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_league_types_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguetype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
