# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_auto_20170823_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='performance',
            name='league_entrant',
        ),
        migrations.AddField(
            model_name='leaguetype',
            name='provider',
            field=models.CharField(default='fpl', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='league',
            name='managers',
            field=models.ManyToManyField(blank=True, through='leagues.LeagueEntrant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leagueentrant',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='leaguetype',
            unique_together=set([('name', 'provider')]),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
