# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20170920_1830'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaguetype',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='leaguetype',
            name='provider',
        ),
    ]
