# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='managers',
            field=models.ManyToManyField(to='leagues.Manager'),
        ),
    ]
