# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_league_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
