# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 09:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0005_auto_20170920_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid_out', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
                ('paid_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PositionPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid_out', models.BooleanField()),
                ('position', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
                ('paid_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='positionpayout',
            unique_together=set([('league', 'name', 'position')]),
        ),
        migrations.AlterUniqueTogether(
            name='periodpayout',
            unique_together=set([('league', 'name', 'start_date', 'end_date')]),
        ),
    ]
