# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 20:00
from __future__ import unicode_literals

from django.db import migrations



def forwards_func(apps, schema_editor):
    LeagueType = apps.get_model('leagues', 'LeagueType')
    db_alias = schema_editor.connection.alias
    LeagueType.objects.using(db_alias).bulk_create([
        LeagueType(name='Classic'),
        LeagueType(name='Head To Head'),
        LeagueType(name='Draft')
    ])

def reverse_func(apps, schema_editor):
    LeagueType = apps.get_model('leagues', 'LeagueType')
    db_alias = schema_editor.connection.alias
    LeagueType.objects.using(db_alias).filter(name='Classic').delete()
    LeagueType.objects.using(db_alias).filter(name='Head To Head').delete()
    LeagueType.objects.using(db_alias).filter(name='Draft').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_auto_20170920_1852'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
