# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_league_entry_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerLeaguePerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.IntegerField()),
                ('score', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagues.Manager')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='managerleagueperformance',
            unique_together=set([('gameweek', 'manager', 'league')]),
        ),
    ]
