# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_auto_20170821_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='leagues_paid',
            field=models.ManyToManyField(to='leagues.League'),
        ),
    ]
