# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_manager_leagues_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='managers',
            field=models.ManyToManyField(blank=True, to='leagues.Manager'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='leagues_paid',
            field=models.ManyToManyField(blank=True, to='leagues.League'),
        ),
    ]
