# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 22:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0009_auto_20170921_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='managers',
            new_name='entrants',
        ),
        migrations.RenameField(
            model_name='leagueentrant',
            old_name='manager',
            new_name='entrant',
        ),
        migrations.AlterUniqueTogether(
            name='leagueentrant',
            unique_together=set([('entrant', 'league')]),
        ),
    ]
