# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_auto_20170921_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payout',
            old_name='paid_to',
            new_name='winner',
        ),
    ]
