# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0011_auto_20170922_0006'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payout',
            unique_together=set([('league', 'position', 'start_date', 'end_date')]),
        ),
    ]
