# Generated by Django 2.0.2 on 2018-05-15 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0014_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leagues.Season'),
            preserve_default=False,
        ),
    ]
