# Generated by Django 2.1 on 2018-08-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_league_season'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('start_date', 'end_date')},
        ),
    ]
